=begin
#ACH-Payments

#Simplify payment processes by seamlessly integrating ACH payments straight into your business flow. 

OpenAPI spec version: v1
Contact: gateway@wellsfargo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

require 'uri'

module WellsFargoAchClient
  class OriginateAnACHPaymentApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Originate an ACH payment.
    # Make a payment using the ACH origination resource. This request allows you to make ACH payment using payer (party funding the payment) and payee (party receiving the payment) bank information.
    # @param gateway_company_id Unique value assigned to your company.
    # @param request_id Unique value to track each API call; it will be returned in the header of every response.
    # @param body payment object that needs to be created
    # @param [Hash] opts the optional parameters
    # @return [String]
    def create_payment(gateway_company_id, request_id, body, opts = {})
      data, _status_code, _headers = create_payment_with_http_info(gateway_company_id, request_id, body, opts)
      data
    end

    # Originate an ACH payment.
    # Make a payment using the ACH origination resource. This request allows you to make ACH payment using payer (party funding the payment) and payee (party receiving the payment) bank information.
    # @param gateway_company_id Unique value assigned to your company.
    # @param request_id Unique value to track each API call; it will be returned in the header of every response.
    # @param body payment object that needs to be created
    # @param [Hash] opts the optional parameters
    # @return [Array<(String, Fixnum, Hash)>] String data, response status code and response headers
    def create_payment_with_http_info(gateway_company_id, request_id, body, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OriginateAnACHPaymentApi.create_payment ...'
      end
      # verify the required parameter 'gateway_company_id' is set
      if @api_client.config.client_side_validation && gateway_company_id.nil?
        fail ArgumentError, "Missing the required parameter 'gateway_company_id' when calling OriginateAnACHPaymentApi.create_payment"
      end
      if @api_client.config.client_side_validation && gateway_company_id.to_s.length > 10
        fail ArgumentError, 'invalid value for "gateway_company_id" when calling OriginateAnACHPaymentApi.create_payment, the character length must be smaller than or equal to 10.'
      end

      if @api_client.config.client_side_validation && gateway_company_id.to_s.length < 10
        fail ArgumentError, 'invalid value for "gateway_company_id" when calling OriginateAnACHPaymentApi.create_payment, the character length must be great than or equal to 10.'
      end

      # verify the required parameter 'request_id' is set
      if @api_client.config.client_side_validation && request_id.nil?
        fail ArgumentError, "Missing the required parameter 'request_id' when calling OriginateAnACHPaymentApi.create_payment"
      end
      if @api_client.config.client_side_validation && request_id.to_s.length > 36
        fail ArgumentError, 'invalid value for "request_id" when calling OriginateAnACHPaymentApi.create_payment, the character length must be smaller than or equal to 36.'
      end

      if @api_client.config.client_side_validation && request_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "request_id" when calling OriginateAnACHPaymentApi.create_payment, the character length must be great than or equal to 1.'
      end

      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling OriginateAnACHPaymentApi.create_payment"
      end
      # resource path
      local_var_path = '/payments'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])
      header_params[:'gateway-company-id'] = gateway_company_id
      header_params[:'request-id'] = request_id

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(body)
      auth_names = ['Bearer']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'String')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OriginateAnACHPaymentApi#create_payment\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
