=begin
#ACH-Payments

#Simplify payment processes by seamlessly integrating ACH payments straight into your business flow. 

OpenAPI spec version: v1
Contact: gateway@wellsfargo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

require 'spec_helper'
require 'json'

# Unit tests for WellsFargoAchClient::OriginateAnACHPaymentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OriginateAnACHPaymentApi' do
  before do
    # run before each test
    @instance = WellsFargoAchClient::OriginateAnACHPaymentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OriginateAnACHPaymentApi' do
    it 'should create an instance of OriginateAnACHPaymentApi' do
      expect(@instance).to be_instance_of(WellsFargoAchClient::OriginateAnACHPaymentApi)
    end
  end

  # unit tests for create_payment
  # Originate an ACH payment.
  # Make a payment using the ACH origination resource. This request allows you to make ACH payment using payer (party funding the payment) and payee (party receiving the payment) bank information.
  # @param gateway_company_id Unique value assigned to your company.
  # @param request_id Unique value to track each API call; it will be returned in the header of every response.
  # @param body payment object that needs to be created
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'create_payment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
