=begin
#ACH-Payments

#Simplify payment processes by seamlessly integrating ACH payments straight into your business flow. 

OpenAPI spec version: v1
Contact: gateway@wellsfargo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WellsFargoAchClient::ErrorsDEF
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ErrorsDEF' do
  before do
    # run before each test
    @instance = WellsFargoAchClient::ErrorsDEF.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErrorsDEF' do
    it 'should create an instance of ErrorsDEF' do
      expect(@instance).to be_instance_of(WellsFargoAchClient::ErrorsDEF)
    end
  end
  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
