=begin
#ACH-Payments

#Simplify payment processes by seamlessly integrating ACH payments straight into your business flow. 

OpenAPI spec version: v1
Contact: gateway@wellsfargo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

# Common files
require 'wells_fargo_ach_client/api_client'
require 'wells_fargo_ach_client/api_error'
require 'wells_fargo_ach_client/version'
require 'wells_fargo_ach_client/configuration'

# Models
require 'wells_fargo_ach_client/models/address_def'
require 'wells_fargo_ach_client/models/adjustment_def'
require 'wells_fargo_ach_client/models/bank_information_def'
require 'wells_fargo_ach_client/models/error_def'
require 'wells_fargo_ach_client/models/errors_def'
require 'wells_fargo_ach_client/models/invoice_def'
require 'wells_fargo_ach_client/models/invoice_def_adjustment_information'
require 'wells_fargo_ach_client/models/invoice_information_def'
require 'wells_fargo_ach_client/models/payee_def'
require 'wells_fargo_ach_client/models/payer_def'
require 'wells_fargo_ach_client/models/payment_def'
require 'wells_fargo_ach_client/models/payment_status_def'

# APIs
require 'wells_fargo_ach_client/api/check_individual_ach_payment_status_api'
require 'wells_fargo_ach_client/api/originate_an_ach_payment_api'

module WellsFargoAchClient
  class << self
    # Customize default settings for the SDK using block.
    #   WellsFargoAchClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
